<?php


namespace App\Repositories;


use App\Interactors\GoogleSheetsInteractor;
use App\Models\Ticket;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class TicketsRepository extends BaseRepository
{
    /**
     * @return string
     */
    protected function getModelClass()
    {
        return Ticket::class;
    }

    protected function getColumnsForSelect(): array
    {
        return ['id', 'ticket_start_date', 'ticket_end_date',
            'ticket_bought_date', 'ticket_count_type_id', 'ticket_event_type_id',
            'student_id', 'teacher_id', 'is_in_pair',
        ];
    }

    protected function getPaginateCount(): int
    {
        return 10;
    }

    function getAllItemsQuery(): Builder
    {
        return parent::getAllItemsQuery()->orderByDesc('id');
    }


    function getAllItemsWithRelationsQuery(): Builder
    {
        return parent::getAllItemsWithRelationsQuery()->with(['student:id,name', 'teacher:id,name', 'ticketEventType:id,name', 'ticketCountType:id,name']);
    }

    function createItem(): Model
    {
        return parent::createItem();
    }


    function storeItem($data): Model
    {
        $ans = parent::storeItem($data);
        $volochkovInteractor = new GoogleSheetsInteractor();
        $volochkovInteractor->registerTicket($ans);
        return $ans;
    }


    function updateItem($data, $id)
    {
        return parent::updateItem($data, $id); // TODO: Change the autogenerated stub
    }

    function destroyItem($id)
    {
        $ticket = $this->startConditions()::find($id);
        $lessonsLeft = $ticket->studentsTicketTypesLessonsLeft;
        if($lessonsLeft){
            $lessonsLeft->ticket_id = 1;
            $lessonsLeft->save();
        }
        $result = $this->startConditions()::destroy($id);
        return $result;
    }


}
